return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 17,
  height = 22,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 83,
  properties = {},
  tilesets = {
    {
      name = "Neon Walls",
      firstgid = 1,
      filename = "../../tilesets/neon_bg.tsx",
      exportfilename = "../../tilesets/neon_bg.lua"
    },
    {
      name = "Neon Floor",
      firstgid = 257,
      filename = "../../tilesets/neon_floor.tsx",
      exportfilename = "../../tilesets/neon_floor.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 17,
      height = 22,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 49, 0, 296, 49, 0, 0, 0, 269, 293, 293, 293, 293, 293,
        258, 0, 0, 0, 49, 0, 296, 9, 50, 2, 0, 263, 282, 293, 293, 293, 293,
        276, 0, 0, 0, 49, 296, 296, 0, 0, 49, 0, 0, 263, 275, 275, 275, 275,
        287, 258, 0, 0, 49, 296, 296, 0, 1, 25, 50, 2, 0, 0, 0, 0, 49,
        275, 264, 0, 1, 10, 296, 296, 296, 49, 296, 296, 49, 0, 0, 0, 1, 10,
        0, 0, 0, 49, 0, 296, 296, 296, 9, 2, 296, 17, 50, 50, 50, 10, 0,
        0, 0, 0, 49, 0, 0, 296, 296, 0, 17, 50, 10, 0, 0, 0, 0, 0,
        0, 0, 1, 10, 0, 0, 0, 0, 0, 49, 0, 0, 296, 296, 296, 296, 296,
        0, 0, 49, 0, 0, 0, 0, 0, 1, 10, 296, 296, 296, 296, 296, 296, 0,
        0, 1, 10, 0, 0, 0, 0, 1, 10, 0, 296, 296, 296, 296, 296, 1, 50,
        0, 49, 0, 296, 296, 296, 0, 49, 296, 296, 296, 296, 296, 296, 0, 49, 0,
        0, 49, 296, 296, 296, 296, 296, 49, 0, 296, 296, 0, 0, 0, 0, 49, 0,
        0, 49, 296, 296, 296, 0, 0, 49, 0, 0, 0, 0, 0, 0, 1, 10, 0,
        0, 49, 0, 0, 0, 0, 0, 49, 257, 270, 270, 270, 270, 258, 49, 0, 0,
        0, 49, 0, 0, 0, 0, 0, 9, 269, 293, 293, 293, 293, 287, 270, 258, 0,
        0, 49, 0, 296, 0, 0, 0, 0, 263, 275, 275, 282, 293, 293, 293, 276, 0,
        0, 9, 2, 296, 296, 0, 296, 0, 0, 0, 0, 263, 275, 275, 275, 264, 0,
        0, 0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0,
        0, 0, 9, 50, 2, 0, 296, 296, 296, 0, 0, 0, 49, 0, 0, 0, 0,
        2, 0, 0, 0, 9, 50, 2, 296, 296, 0, 1, 50, 10, 0, 257, 270, 270,
        9, 2, 0, 0, 0, 0, 9, 2, 296, 0, 49, 0, 0, 0, 269, 293, 293,
        0, 49, 0, 0, 0, 0, 0, 49, 296, 0, 49, 0, 0, 257, 288, 293, 293
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "floormirror",
      class = "objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 520,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 680,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 560,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 520,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 480,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 860,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "darkworld_start/start",
            ["marker"] = "entry_climb"
          }
        },
        {
          id = 18,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 320,
          y = 800,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 120,
          y = 600,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 240,
          y = 720,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 80,
          y = 440,
          width = 120,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 120,
          y = 400,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 320,
          y = 400,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 200,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 600,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 360,
          y = 160,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 240,
          y = 0,
          width = 40,
          height = 280,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 200,
          y = 80,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 480,
          y = 280,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 240,
          y = -20,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "darkworld_start/surface_reveal",
            ["marker"] = "entry_climb"
          }
        },
        {
          id = 57,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 660,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "darkworld_start/start_treasure",
            ["marker"] = "entry_climb"
          }
        },
        {
          id = 59,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 400,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 280,
          y = 760,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 160,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 240,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "climbarea",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 72 }
          }
        },
        {
          id = 72,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 79 }
          }
        },
        {
          id = 80,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 81 }
          }
        },
        {
          id = 81,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 79 }
          }
        },
        {
          id = 82,
          name = "chest",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 620,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["item"] = "neonwrist"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 29,
          name = "bottom",
          type = "",
          shape = "point",
          x = 340,
          y = 820,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["player_state"] = "CLIMB"
          }
        },
        {
          id = 30,
          name = "spawn",
          type = "",
          shape = "point",
          x = 460,
          y = 380,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["player_state"] = "CLIMB"
          }
        },
        {
          id = 55,
          name = "top",
          type = "",
          shape = "point",
          x = 260,
          y = 60,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["player_state"] = "CLIMB"
          }
        },
        {
          id = 58,
          name = "right",
          type = "",
          shape = "point",
          x = 620,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["player_state"] = "CLIMB"
          }
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "point",
          x = 400,
          y = 560,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
